import React, { createContext, useContext, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { ApiError, request } from "./api/client";
import "./styles.css";

export const AuthContext = createContext(null);
const useAuth = () => useContext(AuthContext);
const message = (error) => error instanceof ApiError ? error.message : "Please try again shortly.";

export function AuthProvider({ children }) {
  const [session, setSession] = useState(() => JSON.parse(localStorage.getItem("hotel_customer_session") || "null"));
  const save = (next) => { localStorage.setItem("hotel_customer_session", JSON.stringify(next)); setSession(next); };
  const logout = () => { localStorage.removeItem("hotel_customer_session"); setSession(null); };
  return <AuthContext.Provider value={{ session, save, logout }}>{children}</AuthContext.Provider>;
}
export function Protected({ children }) { const { session } = useAuth(); return session?.user?.role === "customer" ? children : <Navigate to="/login" replace />; }
function Shell({ children }) { const { session, logout } = useAuth(); return <><header><Link className="brand" to="/rooms">Aurora Stay</Link><nav><Link to="/rooms">Rooms</Link>{session && <Link to="/bookings">My bookings</Link>}{session ? <button onClick={logout}>Logout</button> : <Link to="/login">Login</Link>}</nav></header><main>{children}</main></>; }
export function FormAuth({ register = false }) {
  const { save } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ name: "", email: "", phone: "", password: "" }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); setBusy(true); setError(""); try { const body = register ? form : { email: form.email, password: form.password }; const result = await request(`/auth/${register ? "register" : "login"}`, { method: "POST", body }); if (result.user.role !== "customer") throw new Error("This is a manager account. Please use the manager portal."); save({ token: result.access_token, user: result.user }); navigate("/rooms"); } catch (e) { setError(message(e) || e.message); } finally { setBusy(false); } }
  return <section className="auth card"><h1>{register ? "Create your guest account" : "Welcome back"}</h1><form onSubmit={submit}>{register && <label>Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label>}<label>Email<input type="email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label>{register && <label>Phone<input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></label>}<label>Password<input type="password" minLength="8" required value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label>{error && <p className="error">{error}</p>}<button disabled={busy}>{busy ? "Please wait…" : register ? "Register" : "Login"}</button></form><p>{register ? <Link to="/login">Already have an account? Login</Link> : <Link to="/register">New guest? Register</Link>}</p></section>;
}
export function Rooms() { const [rooms, setRooms] = useState([]); const [filters, setFilters] = useState({ check_in: "", check_out: "", capacity: "" }); const [state, setState] = useState({ loading: true, error: "" });
  async function load(event) { event?.preventDefault(); setState({ loading: true, error: "" }); try { const useAvailability = filters.check_in && filters.check_out; const query = new URLSearchParams(); if (useAvailability) { query.set("check_in", filters.check_in); query.set("check_out", filters.check_out); if (filters.capacity) query.set("capacity", filters.capacity); } const result = await request(useAvailability ? `/rooms/available?${query}` : "/rooms?available_only=true"); setRooms(result); } catch (e) { setState({ loading: false, error: message(e) }); return; } setState({ loading: false, error: "" }); }
  useEffect(() => { load(); }, []); return <><section className="hero"><p className="eyebrow">BOOK WITH CONFIDENCE</p><h1>Find your next stay</h1><p>Search hotel rooms and book directly with Aurora Stay.</p></section><form className="filters card" onSubmit={load}><label>Check in<input type="date" value={filters.check_in} onChange={e => setFilters({ ...filters, check_in: e.target.value })} /></label><label>Check out<input type="date" value={filters.check_out} onChange={e => setFilters({ ...filters, check_out: e.target.value })} /></label><label>Guests<input type="number" min="1" value={filters.capacity} onChange={e => setFilters({ ...filters, capacity: e.target.value })} /></label><button>Check availability</button></form>{state.error && <p className="error">{state.error}</p>}{state.loading ? <p>Loading rooms…</p> : rooms.length ? <section className="grid">{rooms.map(room => <article className="card" key={room.room_id}><p className="eyebrow">{room.room_type}</p><h2>Room {room.room_number}</h2><p>Sleeps up to {room.capacity} guests</p><strong>₹{room.price_per_night} / night</strong><Link className="button" to={`/book?room=${room.room_id}`}>Book this room</Link></article>)}</section> : <p className="empty">No rooms are available for those dates.</p>}</>; }
export function Book() { const { session } = useAuth(); const navigate = useNavigate(); const roomId = new URLSearchParams(location.search).get("room") || ""; const [form, setForm] = useState({ room_id: roomId, check_in: "", check_out: "", guests: 1 }); const [result, setResult] = useState(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e) { e.preventDefault(); setBusy(true); setError(""); try { const booking = await request("/bookings", { token: session.token, method: "POST", body: { ...form, room_id: Number(form.room_id), guests: Number(form.guests), customer_id: session.user.customer_id } }); setResult(booking); } catch (e) { setError(message(e)); } finally { setBusy(false); } }
  if (result) return <section className="card"><h1>Booking confirmed</h1><p>Booking #{result.booking_id} is {result.status}.</p>{result.welcome_offer && <p className="success">Welcome offer applied: {result.welcome_offer.discount}% discount.</p>}<Link className="button" to={`/bookings/${result.booking_id}`}>View booking</Link></section>;
  return <section className="card"><h1>Complete your booking</h1><form onSubmit={submit}><label>Room ID<input required type="number" value={form.room_id} onChange={e => setForm({ ...form, room_id: e.target.value })} /></label><label>Check in<input required type="date" value={form.check_in} onChange={e => setForm({ ...form, check_in: e.target.value })} /></label><label>Check out<input required type="date" value={form.check_out} onChange={e => setForm({ ...form, check_out: e.target.value })} /></label><label>Guests<input required type="number" min="1" value={form.guests} onChange={e => setForm({ ...form, guests: e.target.value })} /></label>{error && <p className="error">{error}</p>}<button disabled={busy}>{busy ? "Booking…" : "Confirm booking"}</button></form></section>; }
export function Bookings() { const { session } = useAuth(); const [data, setData] = useState([]); const [error, setError] = useState(""); useEffect(() => { request(`/customers/${session.user.customer_id}/bookings`, { token: session.token }).then(setData).catch(e => setError(message(e))); }, [session]); return <section><h1>My bookings</h1>{error && <p className="error">{error}</p>}{data.length ? <div className="table-wrap"><table><thead><tr><th>ID</th><th>Room</th><th>Dates</th><th>Status</th><th>Amount</th></tr></thead><tbody>{data.map(b => <tr key={b.booking_id}><td><Link to={`/bookings/${b.booking_id}`}>#{b.booking_id}</Link></td><td>{b.room_type} · {b.room_number}</td><td>{b.check_in} → {b.check_out}</td><td><span className="badge">{b.status}</span></td><td>₹{b.booking_amount}</td></tr>)}</tbody></table></div> : <p className="empty">You have no bookings yet.</p>}</section>; }
function BookingDetail() { const { id } = useParams(); const { session } = useAuth(); const [booking, setBooking] = useState(null); const [reason, setReason] = useState(""); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); useEffect(() => { request(`/bookings/${id}`, { token: session.token }).then(setBooking).catch(e => setError(message(e))); }, [id, session]); async function cancel() { try { const response = await request(`/bookings/${id}/cancellation-request`, { token: session.token, method: "POST", body: { reason } }); setNotice(`Cancellation request #${response.request_id} is pending manager review.`); setBooking({ ...booking, status: "cancel_pending" }); } catch (e) { setError(message(e)); } }
  if (error) return <p className="error">{error}</p>; if (!booking) return <p>Loading booking…</p>; return <section className="card"><h1>Booking #{booking.booking_id}</h1><p>{booking.room_type} · Room {booking.room_number}</p><p>{booking.check_in} → {booking.check_out} · {booking.guests} guests</p><p><strong>₹{booking.final_amount}</strong> · <span className="badge">{booking.status}</span></p>{booking.welcome_offer && <p className="success">Welcome offer: {booking.welcome_offer.discount}% discount</p>}{notice ? <p className="success">{notice}</p> : booking.status !== "cancelled" && <><label>Cancellation reason<textarea value={reason} onChange={e => setReason(e.target.value)} /></label><button className="danger" onClick={cancel}>Request cancellation</button></>}{error && <p className="error">{error}</p>}</section>; }
export function Retention() { const { requestId } = useParams(); const { session } = useAuth(); const [data, setData] = useState(null); const [error, setError] = useState(""); useEffect(() => { request(`/bookings/retention-requests/${requestId}`, { token: session.token }).then(setData).catch(e => setError(message(e))); }, [requestId, session]); if (error) return <p className="error">{error}</p>; if (!data) return <p>Loading retention status…</p>; return <section className="card"><h1>Retention request #{data.request_id}</h1><p>Status: <span className="badge">{data.status}</span></p>{data.offer ? <><h2>Your hotel offer</h2><p>{data.offer.description}</p><strong>{data.offer.discount ? `${data.offer.discount}% discount` : data.offer.offer_type}</strong><p className="muted">Customer acceptance/rejection will be available in a later phase.</p></> : <p className="empty">No finalized customer offer is available yet. Your booking remains under review.</p>}</section>; }
export function App() { return <AuthProvider><Shell><Routes><Route path="/login" element={<FormAuth />} /><Route path="/register" element={<FormAuth register />} /><Route path="/rooms" element={<Rooms />} /><Route path="/book" element={<Protected><Book /></Protected>} /><Route path="/bookings" element={<Protected><Bookings /></Protected>} /><Route path="/bookings/:id" element={<Protected><BookingDetail /></Protected>} /><Route path="/retention/:requestId" element={<Protected><Retention /></Protected>} /><Route path="*" element={<Navigate to="/rooms" replace />} /></Routes></Shell></AuthProvider>; }
if (!import.meta.env.VITEST) createRoot(document.getElementById("root")).render(<BrowserRouter><App /></BrowserRouter>);
